version: '3.8'

services:
  backend1:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres

  backend2:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend1
      - backend2

  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - frontend
      - backend1
      - backend2
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html

volumes:
  pgdata:

